name: Build and Deploy

on:
  push:
    branches: [master] # This is only for demo as currently we are using main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

      - name: Build Docker image
        run: docker build -t docuploader .

    # Additional steps for pushing to Docker registry, deployment, etc.
